### PR TITLE
fix(failover): failover to available replicas if master is not starting

### LINKED ISSUE #188: No failover after replica is OOM Killed
I'm converting a Redis install which only needed 256Mi of RAM and remained stable for months.  In using Dragonfly the same load (Just ArgoCD and Immich) and Dragonfly has been OOM killed with 256Mi, 512Mi, 768Mi, I bumped to 1Gi just to keep the instances up.  It seems like a memory leak issue as the number of items held is not going past ~3k.

Anyway, the  issue I have is more with the operator not being able to handle the failed instance or being able to fail-over to one of the other instances which are healthy and idle.

Environment
K3s `v1.29.4+k3s1` on bare metal Ubuntu 22.04.3
X86 all nodes have 64GB RAM or more
6 nodes

`cluster.yaml` file:
```
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  # renovate: datasource=github-releases depName=dragonflydb/dragonfly
  image: ghcr.io/dragonflydb/dragonfly:v1.18.1
  replicas: 3
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --default_lua_flags=allow-undeclared-keys

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 768Mi
```

Instance `dragonfly-1` was OOM killed at 768Mi usage. The instance was unable to start and kept crash looping that its port was already in-use:
```
I20240525 20:38:31.923871     1 dfly_main.cc:642] Starting dragonfly df-v1.18.0-3dd6c4959c3056d6f007cc4001e0923302a566a2
I20240525 20:38:31.924072     1 dfly_main.cc:705] Max memory limit is: 768.00MiB
I20240525 20:38:31.927839     8 uring_proactor.cc:182] IORing with 1024 entries, allocated 102720 bytes, cq_entries is 2048
I20240525 20:38:32.001828     1 proactor_pool.cc:147] Running 2 io threads
E20240525 20:38:32.003954     1 dfly_main.cc:269] Failed to open admin socket any:9999, error: Address already in use
E20240525 20:38:32.004125     1 dfly_main.cc:280] Could not open port 6379, error: Address already in use
```

The operator was writing this out approximately 30x per second for several hours:
```
2024-05-25T20:39:46Z	INFO	Received	{"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "Pod": {"name":"dragonfly-1","namespace":"dragonfly"}, "namespace": "dragonfly", "name": "dragonfly-1", "reconcileID": "c993bfad-1a5f-468d-859a-0776af4e6330", "pod": {"namespace": "dragonfly", "name": "dragonfly-1"}}
2024-05-25T20:39:46Z	INFO	Pod is not ready yet	{"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "Pod": {"name":"dragonfly-1","namespace":"dragonfly"}, "namespace": "dragonfly", "name": "dragonfly-1", "reconcileID": "c993bfad-1a5f-468d-859a-0776af4e6330"}
2024-05-25T20:39:51Z	INFO	Received	{"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "Pod": {"name":"dragonfly-1","namespace":"dragonfly"}, "namespace": "dragonfly", "name": "dragonfly-1", "reconcileID": "b8e3f841-c0e0-4ada-a55a-6516249e9043", "pod": {"namespace": "dragonfly", "name": "dragonfly-1"}}
2024-05-25T20:39:51Z	INFO	Pod is not ready yet	{"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "Pod": {"name":"dragonfly-1","namespace":"dragonfly"}, "namespace": "dragonfly", "name": "dragonfly-1", "reconcileID": "b8e3f841-c0e0-4ada-a55a-6516249e9043"}
```

Instances `dragonfly-0` and `dragonfly-2` showed no errors:
```
I20240522 16:13:01.178887     1 dfly_main.cc:705] Max memory limit is: 768.00MiB
I20240522 16:13:01.183228     9 uring_proactor.cc:182] IORing with 1024 entries, allocated 102720 bytes, cq_entries is 2048
I20240522 16:13:01.259305     1 proactor_pool.cc:147] Running 2 io threads
I20240522 16:13:01.261718     1 dfly_main.cc:271] Listening on admin socket any:9999
I20240522 16:13:01.279654     1 server_family.cc:721] Host OS: Linux 5.15.0-107-generic x86_64 with 2 threads
I20240522 16:13:01.291339     1 snapshot_storage.cc:108] Load snapshot: Searching for snapshot in directory: "/data"
W20240522 16:13:01.291486     1 server_family.cc:814] Load snapshot: No snapshot found
I20240522 16:13:01.303339     8 listener_interface.cc:101] sock[8] AcceptServer - listening on port 6379
I20240522 16:13:01.307965     9 listener_interface.cc:101] sock[7] AcceptServer - listening on port 9999
I20240522 16:13:01.562538     9 version_monitor.cc:174] Your current version '1.18.0' is not the latest version. A newer version '1.18.1' is now available. Please consider an update.
I20240522 16:13:16.472314     9 server_family.cc:2416] Replicating 10.42.0.109:9999
I20240522 16:13:16.489886     9 replica.cc:535] Started full sync with 10.42.0.109:9999
I20240522 16:13:16.527722     9 replica.cc:555] full sync finished in 52 ms
I20240522 16:13:16.527866     9 replica.cc:636] Transitioned into stable sync
```

I had to manually delete the `dragonfly-1` and let it get re-created, once I did that the clients (ArgoCD & Immich) became responsive again.

Q: Even if the operator is unable to deal with the crash looping instance, should it not be able to fail-over to one of the other instances?

---

I suspected a memory leak only due to how the instance `dragonfly-1` RAM consumption looks:
image

The other 2 instances both had a pattern like this, where they seemed fine for a few days before memory consumption ramped up:
image

### PR DESCRIPTION
**Pull request by Abhra303**
Closes #188

### CODE REVIEW

File: internal/controller/dragonfly_pod_lifecycle_controller.go [hunk 1]
```diff
@@ -69,6 +72,30 @@ func (r *DfPodLifeCycleReconciler) Reconcile(ctx context.Context, req ctrl.Reque
 		return ctrl.Result{}, nil
 	}
 
+	// Get the role of the pod
+	role, roleExists := pod.Labels[resources.Role]
+	if !isPodReady {
+		restartCount := getRestartCount(pod)
+		if roleExists && role == "master" {
+			// If the master Pod is not ready and has restarted multiple times, initiate failover
+			if restartCount > 5 {
```
Comment (Pothulapati) [inline internal/controller/dragonfly_pod_lifecycle_controller.go]: hmm, 5 makes sense as when there is a problem with starting. 5 times is pretty quick.

**Review by Pothulapati — APPROVED** [review]

File: internal/controller/dragonfly_pod_lifecycle_controller.go (hunk 1 above)
Comment (Abhra303) [reply internal/controller/dragonfly_pod_lifecycle_controller.go]: made the restartCount check `> 0` as there are two possibilites for this - 1) user created the Dragonfly resource but the master is not starting (i.e. keep crashing), in that case we switch the role to one of available replicas. (2) the running master Pod is restarted (e.g. when increasing pod cpu or memory limit/ or due to a bug), in that case it would initiate the failover to one of replicas.

The problem with `restartCount > 5` is that it won't trigger unless the restart count has crossed the "restartCount" limit.
